/*
 * File:         byd_fps12_libbf663x.h
 *
 * Created:	     2017-02-24
 * Description:  BYD fingerprint IC driver library, chip working process oriented
 *
 * Copyright (C) 2017 BYD Company Limited
 *
 */

#ifndef __FPS12_LIBBF66XX_H__
#define __FPS12_LIBBF66XX_H__

#include "byd_fps_libbf663x.h"

//定义寄存器信息
//register of fps12
//analogous circuit: scan time sequence configure.
#define REG_SENSOR_MODE                 0x01
#define REG_TX_CLK_SEL					0x02
#define REG_TX_CLK_H_TIME               0x03
#define REG_SEN_RST_TIME                0x04
#define REG_INIT_TX_SEL                 0x05
#define REG_FP_INIT_NUM                 0x06
#define REG_FP_INIT_ROW                 0x07
#define REG_FP_INIT_COL                 0x08
#define REG_FG_INIT_NUM                 0x09
#define REG_FG_INIT_ROW                 0x0A
//digital circuit: fingerprint scan.
#define REG_FIR_CMD		                0x0B
#define REG_FIR_DATA	                0x0C
#define REG_DIG_INTE_SEL                0x0D
#define REG_FRAME_ADD_NUM	            0x0E
#define REG_SCAN_DATA_CUT_SEL           0x0F
#define REG_FRAME_ADD_CUT_SEL           0x10
#define REG_READ_ROW_CFG0               0x11
#define REG_READ_ROW_CFG1               0x12
#define REG_FPD_DATA		            0x13
#define REG_ERROR_LINE_NUM              0x14
#define REG_SRAM_EMPTY	                0x15
//digital circuit: finger touch on/off check (scan).
#define REG_FG_ROW_START_A              0x16
#define REG_FG_ROW_START_B		        0x17
#define REG_FG_ROW_START_C	            0x18
#define REG_FG_ROW_NUM_AB               0x19
#define REG_FG_ROW_NUM_C                0x1A
#define REG_FINGER_INTE_SEL             0x1B
#define REG_SUB_CUT_SEL                 0x1C
#define REG_FPD_TH_ON_H                 0x1D
#define REG_FPD_TH_ON_L                 0x1E
#define REG_FPD_TH_OFF_H                0x1F
#define REG_FPD_TH_OFF_L                0x20
#define REG_INT_MODE_SET                0x21
#define REG_SUB_SET_L                   0x22
#define REG_SUB_SET_H                   0x23
#define REG_INT_FINGER_NUM              0x24
#define REG_FPD_STATE_L 				0x25
#define REG_FPD_STATE_H		            0x26
#define REG_FINGER_STATE                0x27
#define REG_SUB_VALUE_SEL               0x28
#define REG_SUB_VALUE_H                 0x29
#define REG_SUB_VALUE_L                 0x2A
//FPD test
#define REG_FPD_TEST_MODE               0x2B
#define REG_ADC_DP_DATA_H               0x2C
#define REG_ADC_DP_DATA_L               0x2D
#define REG_TEST_FIR_CTRL               0x2E
//work mode configure.
#define REG_CHIP_MODE                   0x30
#define REG_SCAN_CMD                    0x31
#define REG_AREA0_ROW_START             0x32
#define REG_AREA0_ROW_END	            0x33
#define REG_AREA0_COL_START             0x34
#define REG_AREA0_COL_END	            0x35
#define REG_AREA1_ROW_START             0x36
#define REG_AREA1_ROW_END	            0x37
#define REG_AREA1_COL_START             0x38
#define REG_AREA1_COL_END	            0x39
#define REG_FP_WAIT_TI_H	            0x3A
#define REG_FP_WAIT_TI_L	            0x3B
#define REG_OS_WAIT_TI_H	            0x3C
#define REG_OS_WAIT_TI_L	            0x3D
#define REG_FG_REST_TI1_EN	            0x3E
#define REG_FG_REST_TI1_H	            0x3F
#define REG_FG_REST_TI1_L 		        0x40
#define REG_FG_REST_TI2_H	            0x41
#define REG_FG_REST_TI2_L 		        0x42
#define REG_FP_CYCLE_REST_TI	        0x43
#define REG_FP_SINGLE_REST_TI	        0x44
#define REG_NO_FINGER_NUM_H		        0x45
#define REG_NO_FINGER_NUM_L		        0x46
#define REG_OS_TH_H			            0x47
#define REG_OS_TH_L			            0x48
#define REG_FG_INIT_TIME	            0x49
#define REG_CFG_FLAG		            0x4A
#define REG_FP_INT_FINGER_EN            0x4B
//System set.
#define REG_SOFT_RST		            0x4C
#define REG_INT_STATE		            0x4D
#define REG_FUNCTION_SEL	            0x4E
#define REG_INT_CFG			            0x4F
#define REG_IO_STATE_SEL	            0x50
#define REG_PD_ANA_A		            0x51
#define REG_PD_ANA_B		            0x52
//test.
#define REG_TEST_FP_SCAN                0x53
#define REG_TIMER_TEST_EN               0x54
//Analogous circuit parameters.
#define REG_ADC_I_SEL                   0x55
#define REG_SEN_BUF_I                   0x56
#define REG_IN_PHASE	                0x57
#define REG_SH_I_SEL                    0x58
#define REG_TX_CFG	                    0x59
//SFR Adjust.
#define REG_VTX_SEL_CTRL                0x5A
#define REG_VCAL_SEL_CTRL               0x5B
//cfg byte & finger os.
#define REG_FINGER_OS_DATA_SEL          0x5C
#define REG_FINGER_OS_DATA_H            0x5D
#define REG_FINGER_OS_DATA_L            0x5E
//OTP OP.
#define REG_SFR_OTP_CMD                 0x63
#define REG_SFR_OTP_DATA                0x64
#define REG_OTP_CMD                     0x65
#define REG_OTP_DATA	                0x66
//Adjust & test
#define REG_ADJ_MODE                    0x67
#define REG_ADJ_MUX_EN                  0x68
#define REG_ADJ_INFO_1                  0x69
#define REG_ADJ_INFO_2                  0x6A
#define REG_ADJ_BG_DIG                  0x6B
#define REG_ADJ_OSC100K                 0x6C
#define REG_ADJ_OSC			            0x6D
#define REG_ADJ_BG_FPD	                0x6E
#define REG_ADJ_BG_ANA                  0x6F
#define REG_ADJ_BG_S_I                  0x70
#define REG_ADJ_BG_S	                0x71
#define REG_ADJ_BG_FPD_I                0x72
#define REG_ADJ_VTX_SEL                 0x73
#define REG_ADJ_VCAL_SEL                0x74
#define REG_ANA_TEST	                0x75
#define REG_TEST_CLK_CFG                0x76
#define REG_SRAM_TEST                   0x77
//-------------------------------------------
//
#define CHIP_MODE_IDLE		0
#define CHIP_MODE_FG_DET	1
#define CHIP_MODE_SLEEP		2

#define CHIP_SCAN_CMD_FG_DET    	0
#define CHIP_SCAN_CMD_FP_SCAN    	0x11


#ifdef BYD_FPS_BUF_CFG

#ifdef BYD_FPS_COVER_PLATE
    #define VAL_SENSOR_MODE			1  //4倍放大系数
#else
	#define VAL_SENSOR_MODE			3  //2倍放大系数
#endif

#define VAL_TX_CLK_SEL			0x03//0
#define VAL_TX_CLK_H_TIME		0x09//0x0c
#define VAL_SEN_RST_TIME		0x11
#define VAL_INIT_TX_SEL			1
#define VAL_FP_INIT_NUM			0xcf
#define VAL_FP_INIT_ROW			0
#define VAL_FP_INIT_COL			0
#define VAL_FG_INIT_NUM			0xcf
#define VAL_FG_INIT_ROW			16	//same with REG_FG_ROW_START_A(0x16)
//FP
#ifdef BYD_FPS_COVER_PLATE
	#define VAL_DIG_INTE_SEL				63		//INTE_NUM=(VAL+1)*2 指纹扫描积分次数
#else
    #define VAL_DIG_INTE_SEL				15		//INTE_NUM=(VAL+1)*2
#endif

//#define VAL_SCAN_DATA_CUT_SEL			0x12	//0x11-17, 0x12-18, 0x13-19
#ifdef BYD_FPS_COVER_PLATE
    #define VAL_SCAN_DATA_CUT_SEL			0x14  //指纹扫描数据存储位数截取选择
#else
	#define VAL_SCAN_DATA_CUT_SEL			0x12  //指纹扫描数据存储位数截取选择 //0x11-17, 0x12-18, 0x13-19
#endif

#define VAL_FRAME_ADD_NUM	0x00
#define VAL_FRAME_ADD_CUT_SEL	0x00

#ifdef BYD_FPS_COVER_PLATE
	#define VAL_READ_ROW_CFG0	0x5f      //area0出指纹扫描中断位置
#else
    #define VAL_READ_ROW_CFG0	0x39
#endif

#ifdef BYD_FPS_COVER_PLATE
	#define VAL_READ_ROW_CFG1	0x5f      //area1出指纹扫描中断位置
#else
    #define VAL_READ_ROW_CFG1	0x39
#endif

//FG
#define VAL_FG_ROW_START_A				0x10
#define VAL_FG_ROW_START_B				0x2c
#define VAL_FG_ROW_START_C				0x48

#define VAL_FG_ROW_NUM_AB				0x3F
#define VAL_FG_ROW_NUM_C				0x07

#define VAL_FINGER_INTE_SEL				0
#define VAL_SUB_CUT_SEL					4

#define VAL_FPD_TH_ON_H					0xfb//0xEF
#define VAL_FPD_TH_ON_L					0x00

#define VAL_FPD_TH_OFF_H				0xfe//0xF1
#define VAL_FPD_TH_OFF_L				0x00

#define VAL_INT_MODE_SET12				0x0B
#define VAL_SUB_SET_L					0x12
#define VAL_SUB_SET_H					0x02
#define VAL_INT_FINGER_NUM				0x00


#define VAL_SCAN_CMD					0

#define VAL_AREA0_ROW_START				0
#define VAL_AREA0_ROW_END				0x5f
#define VAL_AREA0_COL_START				0
#define VAL_AREA0_COL_END				0x5f

#define VAL_AREA1_ROW_START				0
#define VAL_AREA1_ROW_END				0x5f
#define VAL_AREA1_COL_START				0
#define VAL_AREA1_COL_END				0x5f

#define VAL_FP_WAIT_TI_H				0
#define VAL_FP_WAIT_TI_L				0x1E//0
#define VAL_OS_WAIT_TI_H				0
#define VAL_OS_WAIT_TI_L				0
#define VAL_FG_REST_TI1_EN				0
#define VAL_FG_REST_TI1_H				0
#define VAL_FG_REST_TI1_L				0xc7
#define VAL_FG_REST_TI2_H				0
#define VAL_FG_REST_TI2_L				0xC7
#define VAL_FP_CYCLE_REST_TI			0x07
#define VAL_FP_SINGLE_REST_TI			0x07
#define VAL_NO_FINGER_NUM_H				0x0F
#define VAL_NO_FINGER_NUM_L				0xA0
#define VAL_OS_TH_H						0xF1
#define VAL_OS_TH_L						0xFF
#define VAL_FG_INIT_TIME				0
#define VAL_FP_INT_FINGER_EN			0

#ifdef BYD_FPS_DECODE_IMAGE
	#define VAL_FUNCTION_SEL				0x00// 0--加密, 1--不加密
#else
	#define VAL_FUNCTION_SEL				0x01
#endif
#define VAL_INT_CFG						0
#define VAL_IO_STATE_SEL				0x00	//0x02
#define VAL_PD_ANA_A					0x00	//0xff
#define VAL_PD_ANA_B					0x00	//0x0e

#define VAL_ADC_I_SEL					2
#define VAL_SEN_BUF_I					1
#define VAL_IN_PHASE					3
#define VAL_SH_I_SEL					2
#define VAL_TX_CFG						0x19
#define SPI_WR			1
#define SPI_RD			0

#ifndef SPI_TRANS_4BYTE

static unsigned char chip_cfg_func_fpd[394]={
	//byd_fps_cfg_ana_seq -10个
	REG_SENSOR_MODE<<1|SPI_WR, VAL_SENSOR_MODE,		//0x56=
	REG_TX_CLK_SEL<<1|SPI_WR, VAL_TX_CLK_SEL,		//FAE参数
	REG_DIG_INTE_SEL<<1|SPI_WR,VAL_DIG_INTE_SEL,
	REG_TX_CLK_H_TIME<<1|SPI_WR,VAL_TX_CLK_H_TIME,
	REG_SEN_RST_TIME<<1|SPI_WR,VAL_SEN_RST_TIME,
	REG_INIT_TX_SEL<<1|SPI_WR,VAL_INIT_TX_SEL,
	REG_FP_INIT_NUM<<1|SPI_WR,VAL_FP_INIT_NUM,
	REG_FP_INIT_ROW<<1|SPI_WR,VAL_FP_INIT_ROW,
	REG_FP_INIT_COL<<1|SPI_WR,VAL_FP_INIT_COL,
	REG_FG_INIT_NUM<<1|SPI_WR,VAL_FG_INIT_NUM,
	REG_FG_INIT_ROW<<1|SPI_WR,VAL_FG_INIT_ROW,
	//byd_fps_cfg_fp_scan
	REG_FPD_TEST_MODE<<1|SPI_WR,0x00,
	REG_FIR_CMD<<1|SPI_WR,0x63,
	//fir系数
	#ifdef BYD_FPS_COVER_PLATE
	REG_FIR_DATA<<1|SPI_WR,0x66,
	REG_FIR_DATA<<1|SPI_WR,0x2f,
	REG_FIR_DATA<<1|SPI_WR,0x5a,
	REG_FIR_DATA<<1|SPI_WR,0x0d,
	REG_FIR_DATA<<1|SPI_WR,0x30,
	REG_FIR_DATA<<1|SPI_WR,0x0f,
	REG_FIR_DATA<<1|SPI_WR,0x28,
	REG_FIR_DATA<<1|SPI_WR,0x11,
	REG_FIR_DATA<<1|SPI_WR,0x44,
	REG_FIR_DATA<<1|SPI_WR,0x13,
	REG_FIR_DATA<<1|SPI_WR,0x84,
	REG_FIR_DATA<<1|SPI_WR,0x15,
	REG_FIR_DATA<<1|SPI_WR,0xea,
	REG_FIR_DATA<<1|SPI_WR,0x17,
	REG_FIR_DATA<<1|SPI_WR,0x74,
	REG_FIR_DATA<<1|SPI_WR,0x1a,
	REG_FIR_DATA<<1|SPI_WR,0x22,
	REG_FIR_DATA<<1|SPI_WR,0x1d,
	REG_FIR_DATA<<1|SPI_WR,0xf6,
	REG_FIR_DATA<<1|SPI_WR,0x1f,
	REG_FIR_DATA<<1|SPI_WR,0xee,
	REG_FIR_DATA<<1|SPI_WR,0x22,
	REG_FIR_DATA<<1|SPI_WR,0x0a,
	REG_FIR_DATA<<1|SPI_WR,0x26,
	REG_FIR_DATA<<1|SPI_WR,0x4c,
	REG_FIR_DATA<<1|SPI_WR,0x29,
	REG_FIR_DATA<<1|SPI_WR,0xb4,
	REG_FIR_DATA<<1|SPI_WR,0x2c,
	REG_FIR_DATA<<1|SPI_WR,0x3e,
	REG_FIR_DATA<<1|SPI_WR,0x30,
	REG_FIR_DATA<<1|SPI_WR,0xec,
	REG_FIR_DATA<<1|SPI_WR,0x33,
	
	REG_FIR_DATA<<1|SPI_WR,0xbc,
	REG_FIR_DATA<<1|SPI_WR,0x37,
	REG_FIR_DATA<<1|SPI_WR,0xae,
	REG_FIR_DATA<<1|SPI_WR,0x3b,
	REG_FIR_DATA<<1|SPI_WR,0xc2,
	REG_FIR_DATA<<1|SPI_WR,0x3f,
	REG_FIR_DATA<<1|SPI_WR,0xf4,
	REG_FIR_DATA<<1|SPI_WR,0x43,
	REG_FIR_DATA<<1|SPI_WR,0x42,
	REG_FIR_DATA<<1|SPI_WR,0x48,
	REG_FIR_DATA<<1|SPI_WR,0xae,
	REG_FIR_DATA<<1|SPI_WR,0x4c,
	REG_FIR_DATA<<1|SPI_WR,0x38,
	REG_FIR_DATA<<1|SPI_WR,0x51,
	REG_FIR_DATA<<1|SPI_WR,0xda,
	REG_FIR_DATA<<1|SPI_WR,0x55,
	REG_FIR_DATA<<1|SPI_WR,0x8e,
	REG_FIR_DATA<<1|SPI_WR,0x5a,
	REG_FIR_DATA<<1|SPI_WR,0x60,
	REG_FIR_DATA<<1|SPI_WR,0x5f,
	REG_FIR_DATA<<1|SPI_WR,0x3e,
	REG_FIR_DATA<<1|SPI_WR,0x64,
	REG_FIR_DATA<<1|SPI_WR,0x2e,
	REG_FIR_DATA<<1|SPI_WR,0x69,
	REG_FIR_DATA<<1|SPI_WR,0x2e,
	REG_FIR_DATA<<1|SPI_WR,0x6e,
	REG_FIR_DATA<<1|SPI_WR,0x38,
	REG_FIR_DATA<<1|SPI_WR,0x73,
	REG_FIR_DATA<<1|SPI_WR,0x4a,
	REG_FIR_DATA<<1|SPI_WR,0x78,
	REG_FIR_DATA<<1|SPI_WR,0x66,
	REG_FIR_DATA<<1|SPI_WR,0x7d,
	                         
	REG_FIR_DATA<<1|SPI_WR,0x84,
	REG_FIR_DATA<<1|SPI_WR,0x82,
	REG_FIR_DATA<<1|SPI_WR,0xa2,
	REG_FIR_DATA<<1|SPI_WR,0x87,
	REG_FIR_DATA<<1|SPI_WR,0xbe,
	REG_FIR_DATA<<1|SPI_WR,0x8c,
	REG_FIR_DATA<<1|SPI_WR,0xd8,
	REG_FIR_DATA<<1|SPI_WR,0x91,
	REG_FIR_DATA<<1|SPI_WR,0xe8,
	REG_FIR_DATA<<1|SPI_WR,0x96,
	REG_FIR_DATA<<1|SPI_WR,0xee,
	REG_FIR_DATA<<1|SPI_WR,0x9b,
	REG_FIR_DATA<<1|SPI_WR,0xe4,
	REG_FIR_DATA<<1|SPI_WR,0xa0,
	REG_FIR_DATA<<1|SPI_WR,0xca,
	REG_FIR_DATA<<1|SPI_WR,0xa5,
	REG_FIR_DATA<<1|SPI_WR,0x9c,
	REG_FIR_DATA<<1|SPI_WR,0xaa,
	REG_FIR_DATA<<1|SPI_WR,0x56,
	REG_FIR_DATA<<1|SPI_WR,0xaf,
	REG_FIR_DATA<<1|SPI_WR,0xf4,
	REG_FIR_DATA<<1|SPI_WR,0xb3,
	REG_FIR_DATA<<1|SPI_WR,0x74,
	REG_FIR_DATA<<1|SPI_WR,0xb8,
	REG_FIR_DATA<<1|SPI_WR,0xd4,
	REG_FIR_DATA<<1|SPI_WR,0xbc,
	REG_FIR_DATA<<1|SPI_WR,0x12,
	REG_FIR_DATA<<1|SPI_WR,0xc1,
	REG_FIR_DATA<<1|SPI_WR,0x28,
	REG_FIR_DATA<<1|SPI_WR,0xc5,
	REG_FIR_DATA<<1|SPI_WR,0x16,
	REG_FIR_DATA<<1|SPI_WR,0xc9,
	                         
	REG_FIR_DATA<<1|SPI_WR,0xda,
	REG_FIR_DATA<<1|SPI_WR,0xcc,
	REG_FIR_DATA<<1|SPI_WR,0x6e,
	REG_FIR_DATA<<1|SPI_WR,0xd0,
	REG_FIR_DATA<<1|SPI_WR,0xd0,
	REG_FIR_DATA<<1|SPI_WR,0xd3,
	REG_FIR_DATA<<1|SPI_WR,0x0a,
	REG_FIR_DATA<<1|SPI_WR,0xd7,
	REG_FIR_DATA<<1|SPI_WR,0xf2,
	REG_FIR_DATA<<1|SPI_WR,0xd9,
	REG_FIR_DATA<<1|SPI_WR,0xbe,
	REG_FIR_DATA<<1|SPI_WR,0xdc,
	REG_FIR_DATA<<1|SPI_WR,0x4a,
	REG_FIR_DATA<<1|SPI_WR,0xdf,
	REG_FIR_DATA<<1|SPI_WR,0x8e,
	REG_FIR_DATA<<1|SPI_WR,0xe1,
	REG_FIR_DATA<<1|SPI_WR,0x98,
	REG_FIR_DATA<<1|SPI_WR,0xe3,
	REG_FIR_DATA<<1|SPI_WR,0x6c,
	REG_FIR_DATA<<1|SPI_WR,0xe5,
	REG_FIR_DATA<<1|SPI_WR,0x02,
	REG_FIR_DATA<<1|SPI_WR,0xe7,
	REG_FIR_DATA<<1|SPI_WR,0x56,
	REG_FIR_DATA<<1|SPI_WR,0xe8,
	REG_FIR_DATA<<1|SPI_WR,0x64,
	REG_FIR_DATA<<1|SPI_WR,0xe9,
	REG_FIR_DATA<<1|SPI_WR,0x2c,
	REG_FIR_DATA<<1|SPI_WR,0xea,
	REG_FIR_DATA<<1|SPI_WR,0xb0,
	REG_FIR_DATA<<1|SPI_WR,0xea,
	REG_FIR_DATA<<1|SPI_WR,0xf2,
	REG_FIR_DATA<<1|SPI_WR,0xea,
	#else
	REG_FIR_DATA<<1|SPI_WR,0x42,
	REG_FIR_DATA<<1|SPI_WR,0x2d,
	REG_FIR_DATA<<1|SPI_WR,0x52,
	REG_FIR_DATA<<1|SPI_WR,0x22,
	REG_FIR_DATA<<1|SPI_WR,0x18,
	REG_FIR_DATA<<1|SPI_WR,0x2e,
	REG_FIR_DATA<<1|SPI_WR,0x64,
	REG_FIR_DATA<<1|SPI_WR,0x3b,
	REG_FIR_DATA<<1|SPI_WR,0x1c,
	REG_FIR_DATA<<1|SPI_WR,0x4a,
	REG_FIR_DATA<<1|SPI_WR,0xda,
	REG_FIR_DATA<<1|SPI_WR,0x59,
	REG_FIR_DATA<<1|SPI_WR,0x52,
	REG_FIR_DATA<<1|SPI_WR,0x6a,
	REG_FIR_DATA<<1|SPI_WR,0x12,
	REG_FIR_DATA<<1|SPI_WR,0x7b,
	REG_FIR_DATA<<1|SPI_WR,0xae,
	REG_FIR_DATA<<1|SPI_WR,0x8b,
	REG_FIR_DATA<<1|SPI_WR,0xa2,
	REG_FIR_DATA<<1|SPI_WR,0x9b,
	REG_FIR_DATA<<1|SPI_WR,0x72,
	REG_FIR_DATA<<1|SPI_WR,0xaa,
	REG_FIR_DATA<<1|SPI_WR,0xa2,
	REG_FIR_DATA<<1|SPI_WR,0xb7,
	REG_FIR_DATA<<1|SPI_WR,0xc4,
	REG_FIR_DATA<<1|SPI_WR,0xc2,
	REG_FIR_DATA<<1|SPI_WR,0x7a,
	REG_FIR_DATA<<1|SPI_WR,0xcb,
	REG_FIR_DATA<<1|SPI_WR,0x74,
	REG_FIR_DATA<<1|SPI_WR,0xd1,
	REG_FIR_DATA<<1|SPI_WR,0x80,
	REG_FIR_DATA<<1|SPI_WR,0xd4,
	
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	                         
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	                         
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	#endif
	//END FIR
	//REG_DIG_INTE_SEL<<1|SPI_WR,VAL_DIG_INTE_SEL,
	REG_FRAME_ADD_NUM<<1|SPI_WR,VAL_FRAME_ADD_NUM,
	REG_SCAN_DATA_CUT_SEL<<1|SPI_WR,VAL_SCAN_DATA_CUT_SEL,
	REG_FRAME_ADD_CUT_SEL<<1|SPI_WR,VAL_FRAME_ADD_CUT_SEL,
	REG_READ_ROW_CFG0<<1|SPI_WR,VAL_READ_ROW_CFG0,
	REG_READ_ROW_CFG1<<1|SPI_WR,VAL_READ_ROW_CFG1,
	//byd_fps_cfg_fg_scan
	REG_FG_ROW_START_A<<1|SPI_WR,VAL_FG_ROW_START_A,//现在是默认配置，后续可能会更改
	REG_FG_ROW_START_B<<1|SPI_WR,VAL_FG_ROW_START_B,
	REG_FG_ROW_START_C<<1|SPI_WR,VAL_FG_ROW_START_C,
	REG_FG_ROW_NUM_AB<<1|SPI_WR,VAL_FG_ROW_NUM_AB,
	REG_FG_ROW_NUM_C<<1|SPI_WR,VAL_FG_ROW_NUM_C,
	REG_FINGER_INTE_SEL<<1|SPI_WR,VAL_FINGER_INTE_SEL,
	REG_SUB_CUT_SEL<<1|SPI_WR,VAL_SUB_CUT_SEL,
	
	REG_FPD_TH_ON_H<<1|SPI_WR,VAL_FPD_TH_ON_H,//FAE参数
	REG_FPD_TH_ON_L<<1|SPI_WR,VAL_FPD_TH_ON_L,
	REG_FPD_TH_OFF_H<<1|SPI_WR,VAL_FPD_TH_OFF_H,
	REG_FPD_TH_OFF_L<<1|SPI_WR,VAL_FPD_TH_OFF_L,
	REG_FG_REST_TI1_H<<1|SPI_WR,VAL_FG_REST_TI1_H,//手指检测快扫描T3,FAE参数
	REG_FG_REST_TI1_L<<1|SPI_WR,VAL_FG_REST_TI1_L,
	REG_FG_REST_TI2_H<<1|SPI_WR,VAL_FG_REST_TI2_H,//手指检测慢扫描T4 FAE参数
	REG_FG_REST_TI2_L<<1|SPI_WR,VAL_FG_REST_TI2_L,
	REG_NO_FINGER_NUM_H<<1|SPI_WR,VAL_NO_FINGER_NUM_H,
	REG_NO_FINGER_NUM_L<<1|SPI_WR,VAL_NO_FINGER_NUM_L,//FAE参数
	
	REG_INT_MODE_SET<<1|SPI_WR,VAL_INT_MODE_SET,
	REG_SUB_SET_L<<1|SPI_WR,VAL_SUB_SET_L,
	REG_SUB_SET_H<<1|SPI_WR,VAL_SUB_SET_H,
	REG_INT_FINGER_NUM<<1|SPI_WR,VAL_INT_FINGER_NUM,
	//mode cfg
	REG_SCAN_CMD<<1|SPI_WR,VAL_SCAN_CMD,
	REG_AREA0_ROW_START<<1|SPI_WR,VAL_AREA0_ROW_START,
	REG_AREA0_ROW_END<<1|SPI_WR,VAL_AREA0_ROW_END,
	REG_AREA0_COL_START<<1|SPI_WR,VAL_AREA0_COL_START,
	REG_AREA0_COL_END<<1|SPI_WR,VAL_AREA0_COL_END,
	REG_AREA1_ROW_START<<1|SPI_WR,VAL_AREA1_ROW_START,
	REG_AREA1_ROW_END<<1|SPI_WR,VAL_AREA1_ROW_END,
	REG_AREA1_COL_START<<1|SPI_WR,VAL_AREA1_COL_START,
	REG_AREA1_COL_END<<1|SPI_WR,VAL_AREA1_COL_END,
	REG_FP_WAIT_TI_H<<1|SPI_WR,VAL_FP_WAIT_TI_H,
	REG_FP_WAIT_TI_L<<1|SPI_WR,VAL_FP_WAIT_TI_L,
	REG_OS_WAIT_TI_H<<1|SPI_WR,VAL_OS_WAIT_TI_H,
	REG_OS_WAIT_TI_L<<1|SPI_WR,VAL_OS_WAIT_TI_L,
	REG_FG_REST_TI1_EN<<1|SPI_WR,VAL_FG_REST_TI1_EN,//手指检测快慢速切换1：固定使用快定时；0：快慢切换模式
	//REG_FG_REST_TI1_H<<1|SPI_WR,VAL_FG_REST_TI1_H,//手指检测快扫描T3,FAE参数
	//REG_FG_REST_TI1_L<<1|SPI_WR,VAL_FG_REST_TI1_L,
	//REG_FG_REST_TI2_H<<1|SPI_WR,VAL_FG_REST_TI2_H,//手指检测慢扫描T4 FAE参数
	//REG_FG_REST_TI2_L<<1|SPI_WR,VAL_FG_REST_TI2_L,
	//REG_NO_FINGER_NUM_H<<1|SPI_WR,VAL_NO_FINGER_NUM_H,
	//REG_NO_FINGER_NUM_L<<1|SPI_WR,VAL_NO_FINGER_NUM_L,//FAE参数
	REG_FP_CYCLE_REST_TI<<1|SPI_WR,VAL_FP_CYCLE_REST_TI,
	REG_FP_SINGLE_REST_TI<<1|SPI_WR,VAL_FP_SINGLE_REST_TI,
	
	REG_OS_TH_H<<1|SPI_WR,VAL_OS_TH_H,
	REG_OS_TH_L<<1|SPI_WR,VAL_OS_TH_L,
	REG_FG_INIT_TIME<<1|SPI_WR,VAL_FG_INIT_TIME,
	REG_FP_INT_FINGER_EN<<1|SPI_WR,VAL_FP_INT_FINGER_EN,//1:发送手指和指纹中断；0：仅发送指纹中断
	//cfg System
	REG_FUNCTION_SEL<<1|SPI_WR,VAL_FUNCTION_SEL,
	REG_INT_CFG<<1|SPI_WR,VAL_INT_CFG,
	REG_IO_STATE_SEL<<1|SPI_WR,VAL_IO_STATE_SEL,
	REG_PD_ANA_A<<1|SPI_WR,VAL_PD_ANA_A,
	REG_PD_ANA_B<<1|SPI_WR,VAL_PD_ANA_B,
	//ana charameter
	REG_ADC_I_SEL<<1|SPI_WR,VAL_ADC_I_SEL,
	REG_SEN_BUF_I<<1|SPI_WR,VAL_SEN_BUF_I,
	REG_IN_PHASE<<1|SPI_WR,VAL_IN_PHASE,
	REG_SH_I_SEL<<1|SPI_WR,VAL_SH_I_SEL,
	REG_TX_CFG<<1|SPI_WR,VAL_TX_CFG,
	
};

#else

static unsigned char chip_cfg_func_fpd[396]={
	REG_SENSOR_MODE<<1|SPI_WR, VAL_SENSOR_MODE,		//0x56=
	REG_TX_CLK_SEL<<1|SPI_WR, VAL_TX_CLK_SEL,		//FAE参数
	REG_DIG_INTE_SEL<<1|SPI_WR,VAL_DIG_INTE_SEL,
	REG_TX_CLK_H_TIME<<1|SPI_WR,VAL_TX_CLK_H_TIME,
	REG_SEN_RST_TIME<<1|SPI_WR,VAL_SEN_RST_TIME,
	REG_INIT_TX_SEL<<1|SPI_WR,VAL_INIT_TX_SEL,
	REG_FP_INIT_NUM<<1|SPI_WR,VAL_FP_INIT_NUM,
	REG_FP_INIT_ROW<<1|SPI_WR,VAL_FP_INIT_ROW,
	REG_FP_INIT_COL<<1|SPI_WR,VAL_FP_INIT_COL,
	REG_FG_INIT_NUM<<1|SPI_WR,VAL_FG_INIT_NUM,
	REG_FG_INIT_ROW<<1|SPI_WR,VAL_FG_INIT_ROW,
	REG_FPD_TEST_MODE<<1|SPI_WR,0x00,
	REG_FIR_CMD<<1|SPI_WR,0x63,
	//fir系数
		#ifdef BYD_FPS_COVER_PLATE
	REG_FIR_DATA<<1|SPI_WR,0x66,
	REG_FIR_DATA<<1|SPI_WR,0x2f,
	REG_FIR_DATA<<1|SPI_WR,0x5a,
	REG_FIR_DATA<<1|SPI_WR,0x0d,
	REG_FIR_DATA<<1|SPI_WR,0x30,
	REG_FIR_DATA<<1|SPI_WR,0x0f,
	REG_FIR_DATA<<1|SPI_WR,0x28,
	REG_FIR_DATA<<1|SPI_WR,0x11,
	REG_FIR_DATA<<1|SPI_WR,0x44,
	REG_FIR_DATA<<1|SPI_WR,0x13,
	REG_FIR_DATA<<1|SPI_WR,0x84,
	REG_FIR_DATA<<1|SPI_WR,0x15,
	REG_FIR_DATA<<1|SPI_WR,0xea,
	REG_FIR_DATA<<1|SPI_WR,0x17,
	REG_FIR_DATA<<1|SPI_WR,0x74,
	REG_FIR_DATA<<1|SPI_WR,0x1a,
	REG_FIR_DATA<<1|SPI_WR,0x22,
	REG_FIR_DATA<<1|SPI_WR,0x1d,
	REG_FIR_DATA<<1|SPI_WR,0xf6,
	REG_FIR_DATA<<1|SPI_WR,0x1f,
	REG_FIR_DATA<<1|SPI_WR,0xee,
	REG_FIR_DATA<<1|SPI_WR,0x22,
	REG_FIR_DATA<<1|SPI_WR,0x0a,
	REG_FIR_DATA<<1|SPI_WR,0x26,
	REG_FIR_DATA<<1|SPI_WR,0x4c,
	REG_FIR_DATA<<1|SPI_WR,0x29,
	REG_FIR_DATA<<1|SPI_WR,0xb4,
	REG_FIR_DATA<<1|SPI_WR,0x2c,
	REG_FIR_DATA<<1|SPI_WR,0x3e,
	REG_FIR_DATA<<1|SPI_WR,0x30,
	REG_FIR_DATA<<1|SPI_WR,0xec,
	REG_FIR_DATA<<1|SPI_WR,0x33,
	
	REG_FIR_DATA<<1|SPI_WR,0xbc,
	REG_FIR_DATA<<1|SPI_WR,0x37,
	REG_FIR_DATA<<1|SPI_WR,0xae,
	REG_FIR_DATA<<1|SPI_WR,0x3b,
	REG_FIR_DATA<<1|SPI_WR,0xc2,
	REG_FIR_DATA<<1|SPI_WR,0x3f,
	REG_FIR_DATA<<1|SPI_WR,0xf4,
	REG_FIR_DATA<<1|SPI_WR,0x43,
	REG_FIR_DATA<<1|SPI_WR,0x42,
	REG_FIR_DATA<<1|SPI_WR,0x48,
	REG_FIR_DATA<<1|SPI_WR,0xae,
	REG_FIR_DATA<<1|SPI_WR,0x4c,
	REG_FIR_DATA<<1|SPI_WR,0x38,
	REG_FIR_DATA<<1|SPI_WR,0x51,
	REG_FIR_DATA<<1|SPI_WR,0xda,
	REG_FIR_DATA<<1|SPI_WR,0x55,
	REG_FIR_DATA<<1|SPI_WR,0x8e,
	REG_FIR_DATA<<1|SPI_WR,0x5a,
	REG_FIR_DATA<<1|SPI_WR,0x60,
	REG_FIR_DATA<<1|SPI_WR,0x5f,
	REG_FIR_DATA<<1|SPI_WR,0x3e,
	REG_FIR_DATA<<1|SPI_WR,0x64,
	REG_FIR_DATA<<1|SPI_WR,0x2e,
	REG_FIR_DATA<<1|SPI_WR,0x69,
	REG_FIR_DATA<<1|SPI_WR,0x2e,
	REG_FIR_DATA<<1|SPI_WR,0x6e,
	REG_FIR_DATA<<1|SPI_WR,0x38,
	REG_FIR_DATA<<1|SPI_WR,0x73,
	REG_FIR_DATA<<1|SPI_WR,0x4a,
	REG_FIR_DATA<<1|SPI_WR,0x78,
	REG_FIR_DATA<<1|SPI_WR,0x66,
	REG_FIR_DATA<<1|SPI_WR,0x7d,
	                         
	REG_FIR_DATA<<1|SPI_WR,0x84,
	REG_FIR_DATA<<1|SPI_WR,0x82,
	REG_FIR_DATA<<1|SPI_WR,0xa2,
	REG_FIR_DATA<<1|SPI_WR,0x87,
	REG_FIR_DATA<<1|SPI_WR,0xbe,
	REG_FIR_DATA<<1|SPI_WR,0x8c,
	REG_FIR_DATA<<1|SPI_WR,0xd8,
	REG_FIR_DATA<<1|SPI_WR,0x91,
	REG_FIR_DATA<<1|SPI_WR,0xe8,
	REG_FIR_DATA<<1|SPI_WR,0x96,
	REG_FIR_DATA<<1|SPI_WR,0xee,
	REG_FIR_DATA<<1|SPI_WR,0x9b,
	REG_FIR_DATA<<1|SPI_WR,0xe4,
	REG_FIR_DATA<<1|SPI_WR,0xa0,
	REG_FIR_DATA<<1|SPI_WR,0xca,
	REG_FIR_DATA<<1|SPI_WR,0xa5,
	REG_FIR_DATA<<1|SPI_WR,0x9c,
	REG_FIR_DATA<<1|SPI_WR,0xaa,
	REG_FIR_DATA<<1|SPI_WR,0x56,
	REG_FIR_DATA<<1|SPI_WR,0xaf,
	REG_FIR_DATA<<1|SPI_WR,0xf4,
	REG_FIR_DATA<<1|SPI_WR,0xb3,
	REG_FIR_DATA<<1|SPI_WR,0x74,
	REG_FIR_DATA<<1|SPI_WR,0xb8,
	REG_FIR_DATA<<1|SPI_WR,0xd4,
	REG_FIR_DATA<<1|SPI_WR,0xbc,
	REG_FIR_DATA<<1|SPI_WR,0x12,
	REG_FIR_DATA<<1|SPI_WR,0xc1,
	REG_FIR_DATA<<1|SPI_WR,0x28,
	REG_FIR_DATA<<1|SPI_WR,0xc5,
	REG_FIR_DATA<<1|SPI_WR,0x16,
	REG_FIR_DATA<<1|SPI_WR,0xc9,
	                         
	REG_FIR_DATA<<1|SPI_WR,0xda,
	REG_FIR_DATA<<1|SPI_WR,0xcc,
	REG_FIR_DATA<<1|SPI_WR,0x6e,
	REG_FIR_DATA<<1|SPI_WR,0xd0,
	REG_FIR_DATA<<1|SPI_WR,0xd0,
	REG_FIR_DATA<<1|SPI_WR,0xd3,
	REG_FIR_DATA<<1|SPI_WR,0x0a,
	REG_FIR_DATA<<1|SPI_WR,0xd7,
	REG_FIR_DATA<<1|SPI_WR,0xf2,
	REG_FIR_DATA<<1|SPI_WR,0xd9,
	REG_FIR_DATA<<1|SPI_WR,0xbe,
	REG_FIR_DATA<<1|SPI_WR,0xdc,
	REG_FIR_DATA<<1|SPI_WR,0x4a,
	REG_FIR_DATA<<1|SPI_WR,0xdf,
	REG_FIR_DATA<<1|SPI_WR,0x8e,
	REG_FIR_DATA<<1|SPI_WR,0xe1,
	REG_FIR_DATA<<1|SPI_WR,0x98,
	REG_FIR_DATA<<1|SPI_WR,0xe3,
	REG_FIR_DATA<<1|SPI_WR,0x6c,
	REG_FIR_DATA<<1|SPI_WR,0xe5,
	REG_FIR_DATA<<1|SPI_WR,0x02,
	REG_FIR_DATA<<1|SPI_WR,0xe7,
	REG_FIR_DATA<<1|SPI_WR,0x56,
	REG_FIR_DATA<<1|SPI_WR,0xe8,
	REG_FIR_DATA<<1|SPI_WR,0x64,
	REG_FIR_DATA<<1|SPI_WR,0xe9,
	REG_FIR_DATA<<1|SPI_WR,0x2c,
	REG_FIR_DATA<<1|SPI_WR,0xea,
	REG_FIR_DATA<<1|SPI_WR,0xb0,
	REG_FIR_DATA<<1|SPI_WR,0xea,
	REG_FIR_DATA<<1|SPI_WR,0xf2,
	REG_FIR_DATA<<1|SPI_WR,0xea,
	#else
	REG_FIR_DATA<<1|SPI_WR,0x42,
	REG_FIR_DATA<<1|SPI_WR,0x2d,
	REG_FIR_DATA<<1|SPI_WR,0x52,
	REG_FIR_DATA<<1|SPI_WR,0x22,
	REG_FIR_DATA<<1|SPI_WR,0x18,
	REG_FIR_DATA<<1|SPI_WR,0x2e,
	REG_FIR_DATA<<1|SPI_WR,0x64,
	REG_FIR_DATA<<1|SPI_WR,0x3b,
	REG_FIR_DATA<<1|SPI_WR,0x1c,
	REG_FIR_DATA<<1|SPI_WR,0x4a,
	REG_FIR_DATA<<1|SPI_WR,0xda,
	REG_FIR_DATA<<1|SPI_WR,0x59,
	REG_FIR_DATA<<1|SPI_WR,0x52,
	REG_FIR_DATA<<1|SPI_WR,0x6a,
	REG_FIR_DATA<<1|SPI_WR,0x12,
	REG_FIR_DATA<<1|SPI_WR,0x7b,
	REG_FIR_DATA<<1|SPI_WR,0xae,
	REG_FIR_DATA<<1|SPI_WR,0x8b,
	REG_FIR_DATA<<1|SPI_WR,0xa2,
	REG_FIR_DATA<<1|SPI_WR,0x9b,
	REG_FIR_DATA<<1|SPI_WR,0x72,
	REG_FIR_DATA<<1|SPI_WR,0xaa,
	REG_FIR_DATA<<1|SPI_WR,0xa2,
	REG_FIR_DATA<<1|SPI_WR,0xb7,
	REG_FIR_DATA<<1|SPI_WR,0xc4,
	REG_FIR_DATA<<1|SPI_WR,0xc2,
	REG_FIR_DATA<<1|SPI_WR,0x7a,
	REG_FIR_DATA<<1|SPI_WR,0xcb,
	REG_FIR_DATA<<1|SPI_WR,0x74,
	REG_FIR_DATA<<1|SPI_WR,0xd1,
	REG_FIR_DATA<<1|SPI_WR,0x80,
	REG_FIR_DATA<<1|SPI_WR,0xd4,
	
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	REG_FIR_DATA<<1|SPI_WR,0xff,
	#endif 
	
	REG_FRAME_ADD_NUM<<1|SPI_WR,VAL_FRAME_ADD_NUM,
	REG_SCAN_DATA_CUT_SEL<<1|SPI_WR,VAL_SCAN_DATA_CUT_SEL,
	REG_FRAME_ADD_CUT_SEL<<1|SPI_WR,VAL_FRAME_ADD_CUT_SEL,
	REG_READ_ROW_CFG0<<1|SPI_WR,VAL_READ_ROW_CFG0,
	REG_READ_ROW_CFG1<<1|SPI_WR,VAL_READ_ROW_CFG1,
	REG_FG_ROW_START_A<<1|SPI_WR,VAL_FG_ROW_START_A,//现在是默认配置，后续可能会更改
	REG_FG_ROW_START_B<<1|SPI_WR,VAL_FG_ROW_START_B,
	REG_FG_ROW_START_C<<1|SPI_WR,VAL_FG_ROW_START_C,
	REG_FG_ROW_NUM_AB<<1|SPI_WR,VAL_FG_ROW_NUM_AB,
	REG_FG_ROW_NUM_C<<1|SPI_WR,VAL_FG_ROW_NUM_C,
	REG_FINGER_INTE_SEL<<1|SPI_WR,VAL_FINGER_INTE_SEL,
	REG_SUB_CUT_SEL<<1|SPI_WR,VAL_SUB_CUT_SEL,
	
	REG_FPD_TH_ON_H<<1|SPI_WR,VAL_FPD_TH_ON_H,
	REG_FPD_TH_ON_L<<1|SPI_WR,VAL_FPD_TH_ON_L,
	REG_FPD_TH_OFF_H<<1|SPI_WR,VAL_FPD_TH_OFF_H,
	REG_FPD_TH_OFF_L<<1|SPI_WR,VAL_FPD_TH_OFF_L,
	REG_FG_REST_TI1_H<<1|SPI_WR,VAL_FG_REST_TI1_H,//手指检测快扫描T3,FAE参数
	REG_FG_REST_TI1_L<<1|SPI_WR,VAL_FG_REST_TI1_L,
	REG_FG_REST_TI2_H<<1|SPI_WR,VAL_FG_REST_TI2_H,//手指检测慢扫描T4 FAE参数
	REG_FG_REST_TI2_L<<1|SPI_WR,VAL_FG_REST_TI2_L,
	REG_NO_FINGER_NUM_H<<1|SPI_WR,VAL_NO_FINGER_NUM_H,
	REG_NO_FINGER_NUM_L<<1|SPI_WR,VAL_NO_FINGER_NUM_L,//FAE参数
	//FAE参数
	REG_INT_MODE_SET<<1|SPI_WR,VAL_INT_MODE_SET,
	REG_SUB_SET_L<<1|SPI_WR,VAL_SUB_SET_L,
	REG_SUB_SET_H<<1|SPI_WR,VAL_SUB_SET_H,
	REG_INT_FINGER_NUM<<1|SPI_WR,VAL_INT_FINGER_NUM,
	//mode cfg
	REG_SCAN_CMD<<1|SPI_WR,VAL_SCAN_CMD,
	REG_AREA0_ROW_START<<1|SPI_WR,VAL_AREA0_ROW_START,
	REG_AREA0_ROW_END<<1|SPI_WR,VAL_AREA0_ROW_END,
	REG_AREA0_COL_START<<1|SPI_WR,VAL_AREA0_COL_START,
	REG_AREA0_COL_END<<1|SPI_WR,VAL_AREA0_COL_END,
	REG_AREA1_ROW_START<<1|SPI_WR,VAL_AREA1_ROW_START,
	REG_AREA1_ROW_END<<1|SPI_WR,VAL_AREA1_ROW_END,
	//截位
	REG_AREA1_COL_START<<1|SPI_WR,VAL_AREA1_COL_START,
	REG_AREA1_COL_END<<1|SPI_WR,VAL_AREA1_COL_END,
	REG_FP_WAIT_TI_H<<1|SPI_WR,VAL_FP_WAIT_TI_H,
	REG_FP_WAIT_TI_L<<1|SPI_WR,VAL_FP_WAIT_TI_L,
	REG_OS_WAIT_TI_H<<1|SPI_WR,VAL_OS_WAIT_TI_H,
	REG_OS_WAIT_TI_L<<1|SPI_WR,VAL_OS_WAIT_TI_L,
	REG_FG_REST_TI1_EN<<1|SPI_WR,VAL_FG_REST_TI1_EN,//手指检测快慢速切换1：固定使用快定时；0：快慢切换模式
	REG_FP_CYCLE_REST_TI<<1|SPI_WR,VAL_FP_CYCLE_REST_TI,
	REG_FP_SINGLE_REST_TI<<1|SPI_WR,VAL_FP_SINGLE_REST_TI,
	
	REG_OS_TH_H<<1|SPI_WR,VAL_OS_TH_H,
	REG_OS_TH_L<<1|SPI_WR,VAL_OS_TH_L,
	REG_FG_INIT_TIME<<1|SPI_WR,VAL_FG_INIT_TIME,
	REG_FP_INT_FINGER_EN<<1|SPI_WR,VAL_FP_INT_FINGER_EN,//1:发送手指和指纹中断；0：仅发送指纹中断
	//cfg System
	REG_FUNCTION_SEL<<1|SPI_WR,VAL_FUNCTION_SEL,
	REG_INT_CFG<<1|SPI_WR,VAL_INT_CFG,
	REG_IO_STATE_SEL<<1|SPI_WR,VAL_IO_STATE_SEL,
	REG_PD_ANA_A<<1|SPI_WR,VAL_PD_ANA_A,
	REG_PD_ANA_B<<1|SPI_WR,VAL_PD_ANA_B,
	//ana charameter
	REG_ADC_I_SEL<<1|SPI_WR,VAL_ADC_I_SEL,
	REG_SEN_BUF_I<<1|SPI_WR,VAL_SEN_BUF_I,
	REG_IN_PHASE<<1|SPI_WR,VAL_IN_PHASE,
	REG_SH_I_SEL<<1|SPI_WR,VAL_SH_I_SEL,
	REG_TX_CFG<<1|SPI_WR,VAL_TX_CFG,
	0xbe,0x00,
};

#endif
#endif


#ifdef BYD_FPS_CFG_SEPERATE

#ifdef BYD_FPS_COVER_PLATE
    #define VAL_SENSOR_MODE			1  //4倍放大系数
#else
	#define VAL_SENSOR_MODE			3  //2倍放大系数
#endif

unsigned char VAL_TX_CLK_SEL12 = 	3;
#define VAL_TX_CLK_H_TIME12		0x09
#define VAL_SEN_RST_TIME		0x11
#define VAL_INIT_TX_SEL			1
#define VAL_FP_INIT_NUM			0xcf
#define VAL_FP_INIT_ROW			0
#define VAL_FP_INIT_COL			0
#define VAL_FG_INIT_NUM			0xcf
#define VAL_FG_INIT_ROW			16//24	//same with REG_FG_ROW_START_A(0x16)

unsigned char  VAL_DIG_INTE_SEL	= 0x0f;//byd_fps_fae_image[1];//INTE_NUM=(VAL+1)*2

#ifdef BYD_FPS_COVER_PLATE
    #define VAL_SCAN_DATA_CUT_SEL			0x14  //指纹扫描数据存储位数截取选择
#else
	#define VAL_SCAN_DATA_CUT_SEL			0x12  //指纹扫描数据存储位数截取选择 //0x11-17, 0x12-18, 0x13-19
#endif

//#define VAL_SCAN_DATA_CUT_SEL			0x14//0x13 //0x12	//0x11-17, 0x12-18, 0x13-19

unsigned char  VAL_READ_ROW_CFG0 = 0x39;//0x5f
unsigned char VAL_READ_ROW_CFG1 = 0x39;//0x5f

#define VAL_FG_ROW_START_A_GEST				0x01//24 0x10
#define VAL_FG_ROW_START_B_GEST				0x2c//44
#define VAL_FG_ROW_START_C_GEST				0x56//80  0x48

#define VAL_FG_ROW_START_A				0x10//24 0x10
#define VAL_FG_ROW_START_B12				0x2c//44
#define VAL_FG_ROW_START_C12				0x48//80  0x48

#define VAL_FG_ROW_NUM_AB				0x3F
#define VAL_FG_ROW_NUM_C				0x07

#define VAL_FINGER_INTE_SEL				0
#define VAL_SUB_CUT_SEL					4

unsigned char VAL_FPD_TH_ON_H = 0xfb;//byd_fps_fae_detect[0];
unsigned char VAL_FPD_TH_ON_L = 0x00;//byd_fps_fae_detect[1];

unsigned char VAL_FPD_TH_OFF_H = 0xfe;//byd_fps_fae_detect[2];
unsigned char VAL_FPD_TH_OFF_L = 0x00;//byd_fps_fae_detect[3];

#define VAL_INT_MODE_SET12				0x0B// 0x13
#define VAL_INT_MODE_SET_FP12          	0x13
#define VAL_SUB_SET_L12					0x05//0x12 0x05 
#define VAL_SUB_SET_H					0x05//0x02 0x05 

#define VAL_INT_FINGER_NUM				0x00

#define VAL_CHIP_MODE					0
#define VAL_SCAN_CMD					0

#define VAL_AREA0_ROW_START				0
#define VAL_AREA0_ROW_END12				0x5f
#define VAL_AREA0_COL_START				0
#define VAL_AREA0_COL_END12				0x5f

#define VAL_AREA1_ROW_START				0
#define VAL_AREA1_ROW_END12				0x5f
#define VAL_AREA1_COL_START				0
#define VAL_AREA1_COL_END12				0x5f

#define VAL_FP_WAIT_TI_H				0
#define VAL_FP_WAIT_TI_L				0x1E//0
#define VAL_OS_WAIT_TI_H				0
#define VAL_OS_WAIT_TI_L				0
#define VAL_FG_REST_TI1_EN				0
unsigned char VAL_FG_REST_TI1_H	= 0x00;//byd_fps_fae_detect[4];
unsigned char VAL_FG_REST_TI1_L	= 0x07;//byd_fps_fae_detect[5];
unsigned char VAL_FG_REST_TI2_H	= 0x00;//byd_fps_fae_detect[6];
unsigned char VAL_FG_REST_TI2_L	= 0xc7;//byd_fps_fae_detect[7];
#define VAL_FP_CYCLE_REST_TI			0x07
#define VAL_FG_SINGLE_REST_TI			0x07
unsigned char VAL_NO_FINGER_NUM_H = 0x0f;//byd_fps_fae_detect[8];
unsigned char VAL_NO_FINGER_NUM_L =	0xa0;//byd_fps_fae_detect[9];
#define VAL_OS_TH_H						0xF1
#define VAL_OS_TH_L						0xFF
#define VAL_FG_INIT_TIME				0
#define VAL_FP_INT_FINGER_EN			0

#define VAL_FUNCTION_SEL				0
#define VAL_INT_CFG						0
#define VAL_IO_STATE_SEL				0x00	//0x02
#define VAL_PD_ANA_A					0x00	//0xff
#define VAL_PD_ANA_B					0x00	//0x0e

#define VAL_ADC_I_SEL					2
#define VAL_SEN_BUF_I					1
#define VAL_IN_PHASE					3
#define VAL_SH_I_SEL					2
#define VAL_TX_CFG						0x19

#endif


//OTP READ ADDRESS
#define OTP_MODULE_ID12             0x30
#define OTP_MODULE_BYTE12           8*2

#define OTP_BAD_POINT_CHIP_START12  0x38//10
#define OTP_BAD_POINT_CHIP12    0x39
#define OTP_BAD_POINT_CHIP_END12   0xB8
 
#define OTP_BAD_POINT_POTTING_START12  0xB9//5
#define OTP_BAD_POINT_POTTING12   0xBA
#define OTP_BAD_POINT_POTTING_END12  0xFB
 
#define OTP_BAD_POINT_MODULE_START12  0xFC
#define OTP_BAD_POINT_MODULE12   0xFD
#define OTP_BAD_POINT_MODULE_END12  0x13D
 
#define OTP_BAD_COLUMN_4712    0x13E
#define OTP_BAD_COLUMN_4812   0x13F
 
#define OTP_OS_DATA_START12    0x140
#define OTP_OS_DATA_END12     0x1C3F
 
#define OTP_COLUMN_ADJ_START12   0x1C40
#define OTP_COLUMN_ADJ_END12    0x1C9F
 
#define OTP_MODULE_INFO_START12   0x1CA0
#define OTP_MODULE_INFO_END12    0x1CBF

#define OTP_MARK12   0x1CC0

#endif