ccflags-y += -I$(srctree)/drivers/spi/mediatek/$(MTK_PLATFORM)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/fingerprint_bf633x
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include

obj-y  := byd_fps_bf663x.o  byd_fps_platform.o byd_fps_gesture_detect.o byd_fps_wakeup.o byd_fps_spi.o byd_fps_libbf663x.o byd_fingerprint.o byd_fps_timer.o



